### PR TITLE
add chrome extension

### PR DESCRIPTION
**Pull request by tonyydl**
Modifying Firefox extension api to Chrome extension api

### CODE REVIEW

**Comment by wildskyf** [comment]
Hi Tony, thanks for your pull request.

But I think it is not necessary for us to maintain two code of same
version, could you please help me to import webextension-polyfill we
mentioned last weekend, and see whether it works or not? Thank you!

Wildsky

Tony Yang <notifications@github.com>於 2019年1月22日 週二，14:58寫道：

**Comment by tonyydl** [comment]
Got it, I will try to import webextension-polyfill to implemented cross-platform extension

**Comment by tonyydl** [comment]
@wildskyf  I successfully imported webextension-polyfill tool that it works fine!

**Comment by wildskyf** [comment]
I just test it and it works well. Thanks!
but I will reorganize commits and remove hot-reload.js after merging this PR. :)

**Pull request merged**
